import { LinksListItem } from "entities/LinksList"
import {
    BabyCarriageIcon,
    BoxIcon,
    CarIcon,
    FemaleIcon,
    HouseIcon,
    LampIcon,
    LaptopIcon,
    MaleIcon,
    ShopBagIcon,
    SoundIcon,
    TabletIcon,
} from "shared/assets/icons/list"

export const catalogList: LinksListItem[] = [
    {
        id: "1",
        title: "Дом",
        Icon: HouseIcon,
        list: [
            { id: "1", text: "Часы", path: "/sub_category" },
            { id: "2", text: "Android приставки", path: "/sub_category" },
            { id: "3", text: "Видеорегистраторы, камеры, домофоны", path: "/sub_category" },
            { id: "4", text: "Телевизоры", path: "/sub_category" },
            { id: "5", text: "Обогреватели", path: "/sub_category" },
            { id: "6", text: "Чайники", path: "/sub_category" },
            { id: "7", text: "Тестеры мультиметры", path: "/sub_category" },
            { id: "8", text: "Вентиляторы", path: "/sub_category" },
        ],
    },
    {
        id: "2",
        title: "Автомобиль",
        Icon: CarIcon,
        list: [
            { id: "1", text: "Часы", path: "/sub_category" },
            { id: "2", text: "Android приставки", path: "/sub_category" },
            { id: "3", text: "Видеорегистраторы, камеры, домофоны", path: "/sub_category" },
            { id: "4", text: "Телевизоры", path: "/sub_category" },
            { id: "5", text: "Обогреватели", path: "/sub_category" },
            { id: "6", text: "Чайники", path: "/sub_category" },
            { id: "7", text: "Тестеры мультиметры", path: "/sub_category" },
            { id: "8", text: "Вентиляторы", path: "/sub_category" },
        ],
    },
    {
        id: "3",
        title: "Световое оборудование",
        Icon: LampIcon,
        list: [
            { id: "1", text: "LED ленты, Гирлянды, Контролеры", path: "/sub_category" },
            { id: "2", text: "Лазеры, Брелки, Лампы", path: "/sub_category" },
            { id: "3", text: "Светодиодные LED вывески", path: "/sub_category" },
            { id: "4", text: "Фонарики", path: "/sub_category" },
        ],
    },
    {
        id: "4",
        title: "Телефоны и планшеты",
        Icon: TabletIcon,
        list: [
            { id: "1", text: "Мобильные телефоны", path: "/sub_category" },
            { id: "2", text: "Планшетные ПК", path: "/sub_category" },
            { id: "3", text: "Аккумуляторы и зарядные устройства", path: "/sub_category" },
            { id: "4", text: "Power Bank", path: "/sub_category" },
            { id: "5", text: "Моноподы для селфи", path: "/sub_category" },
            { id: "6", text: "Кабеля и переходники", path: "/sub_category" },
            { id: "7", text: "Наушники и гарнитуры", path: "/sub_category" },
            { id: "8", text: "Мобильные колонки", path: "/sub_category" },
        ],
    },
    {
        id: "5",
        title: "Компьютерная переферия",
        Icon: LaptopIcon,
        list: [
            { id: "1", text: "Клавиатуры", path: "/sub_category" },
            { id: "2", text: "Мыши", path: "/sub_category" },
            { id: "3", text: "Адаптеры", path: "/sub_category" },
            { id: "4", text: "Кабеля и переходники", path: "/sub_category" },
        ],
    },
    {
        id: "6",
        title: "Звуковое оборудование",
        Icon: SoundIcon,
        list: [
            { id: "1", text: "Усилители звука", path: "/sub_category" },
            { id: "2", text: "MP3 Плееры и флешки", path: "/sub_category" },
            { id: "3", text: "Автомобильные магнитолы", path: "/sub_category" },
            { id: "4", text: "Автомобильные колонки", path: "/sub_category" },
            { id: "5", text: "Наушники и гарнитуры", path: "/sub_category" },
        ],
    },
    {
        id: "7",
        title: "Мужчинам",
        Icon: MaleIcon,
        list: [
            { id: "1", text: "Бритвы, тримеры, для стрижки", path: "/sub_category" },
            { id: "2", text: "Электронные сигареты", path: "/sub_category" },
        ],
    },
    {
        id: "8",
        title: "Женщинам",
        Icon: FemaleIcon,
        list: [
            { id: "1", text: "Бритвы, эпиляторы, стрижки", path: "/sub_category" },
            { id: "2", text: "Косметика", path: "/sub_category" },
            { id: "3", text: "Фены, плойки, бигуди, утюжки", path: "/sub_category" },
            { id: "4", text: "Швейные машинки", path: "/sub_category" },
        ],
    },
    {
        id: "9",
        title: "Детям",
        Icon: BabyCarriageIcon,
        list: [
            { id: "1", text: "Спинер, волчок", path: "/sub_category" },
            { id: "2", text: "Гироборды", path: "/sub_category" },
            { id: "3", text: "Лазеры, Лампы, Брелки", path: "/sub_category" },
            { id: "4", text: "Тетрисы, тамагочи, карманные приставки", path: "/sub_category" },
            { id: "5", text: "Наборы резинок для плетения браслетов", path: "/sub_category" },
        ],
    },
    {
        id: "10",
        title: "Торговля",
        Icon: ShopBagIcon,
        list: [
            { id: "1", text: "Спинер, волчок", path: "/sub_category" },
            { id: "2", text: "Гироборды", path: "/sub_category" },
            { id: "3", text: "Лазеры, Лампы, Брелки", path: "/sub_category" },
        ],
    },
    {
        id: "11",
        title: "Чехлы и плёнки",
        Icon: TabletIcon,
        list: [
            { id: "1", text: "Чехлы для телефонов и планшетов", path: "/sub_category" },
            { id: "2", text: "Защитные стёкла", path: "/sub_category" },
        ],
    },
    {
        id: "12",
        title: "Разное",
        Icon: BoxIcon,
        list: [{ id: "1", text: "Кошельки и портмоне", path: "/sub_category" }],
    },
]
